<script setup lang="ts">
import { computed,nextTick,onMounted,ref,watch } from 'vue';import { MapPin,KeyRound } from '@lucide/vue';import type { Itinerary } from '../types'
const props=defineProps<{itinerary?:Itinerary|null;selectedDay?:number}>(),mapEl=ref<HTMLElement|null>(null),ready=ref(false),mapKey=localStorage.getItem('travelmind_amap_key')||import.meta.env.VITE_AMAP_JS_KEY||''
const points=computed(()=>(props.itinerary?.days||[]).filter(d=>!props.selectedDay||d.day===props.selectedDay).flatMap(d=>d.activities.map(a=>({...a,day:d.day}))).filter(a=>a.poi?.location))
/** 按需加载高德 Web SDK，并绘制当前行程的标记和轨迹。 */
async function renderMap(){if(!mapKey||!mapEl.value||!points.value.length)return;const w=window as any;if(!w.AMap){await new Promise<void>((resolve,reject)=>{const security=localStorage.getItem('travelmind_amap_security')||import.meta.env.VITE_AMAP_SECURITY_CODE;if(security)w._AMapSecurityConfig={securityJsCode:security};const script=document.createElement('script');script.src=`https://webapi.amap.com/maps?v=2.0&key=${encodeURIComponent(mapKey)}`;script.onload=()=>resolve();script.onerror=()=>reject(new Error('地图加载失败'));document.head.appendChild(script)})}await nextTick();const map=new w.AMap.Map(mapEl.value,{zoom:12,mapStyle:'amap://styles/whitesmoke'});const markers=points.value.map((p,i)=>new w.AMap.Marker({position:[p.poi!.location!.longitude,p.poi!.location!.latitude],title:p.name,label:{content:`${i+1}`,direction:'top'}}));map.add(markers);const path=points.value.map(p=>[p.poi!.location!.longitude,p.poi!.location!.latitude]);if(path.length>1)map.add(new w.AMap.Polyline({path,strokeColor:'#c65d3b',strokeWeight:5}));map.setFitView(markers,false,[70,70,70,70]);ready.value=true}
onMounted(renderMap);watch(()=>[props.itinerary,props.selectedDay],renderMap,{deep:true})
</script>
<template><div class="map-canvas"><div v-if="mapKey" ref="mapEl" class="amap-host"></div><div v-if="!mapKey||!ready" class="map-fallback"><div class="map-road road-one"></div><div class="map-road road-two"></div><div class="map-river"></div><div v-for="(point,index) in points.slice(0,5)" :key="point.activity_id" class="map-pin" :style="{left:`${20+(index*17)%65}%`,top:`${22+(index*23)%55}%`}"><span>{{index+1}}</span><small>{{point.name}}</small></div><div v-if="!points.length" class="map-placeholder"><MapPin :size="28"/><strong>路线会显示在这里</strong><small>生成含坐标的行程后，将自动绘制每日轨迹</small></div><div v-else-if="!mapKey" class="map-key-hint"><KeyRound :size="14"/>在设置中填写高德 Key 可启用交互地图</div></div></div></template>
