"""create_travelmind_core_tables

Revision ID: a4b0c868ef89
Revises:
Create Date: 2026-09-29 17:10:41.257769
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4b0c868ef89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_health',
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('average_latency', sa.Float(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('circuit_state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider_name')
    )
    op.create_table('tool_calls',
    sa.Column('tool_call_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('trip_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    op.create_index(op.f('ix_tool_calls_session_id'), 'tool_calls', ['session_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_trip_id'), 'tool_calls', ['trip_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_user_id'), 'tool_calls', ['user_id'], unique=False)
    op.create_index('ix_tool_calls_user_session_trip', 'tool_calls', ['user_id', 'session_id', 'trip_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('personalization_enabled', sa.Boolean(), nullable=False),
    sa.Column('long_term_memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('current_trip_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index('ix_chat_sessions_user_session', 'chat_sessions', ['user_id', 'session_id'], unique=True)
    op.create_table('memory_items',
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('structured_value', sa.JSON(), nullable=True),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('polarity', sa.String(length=16), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index(op.f('ix_memory_items_user_id'), 'memory_items', ['user_id'], unique=False)
    op.create_index('ix_memory_items_user_memory', 'memory_items', ['user_id', 'memory_id'], unique=True)
    op.create_table('rag_sources',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('authorization_status', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_rag_sources_owner_user_id'), 'rag_sources', ['owner_user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_payload', sa.JSON(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_chat_messages_user_session_message', 'chat_messages', ['user_id', 'session_id', 'message_id'], unique=True)
    op.create_table('memory_evidence',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('trip_id', sa.String(length=64), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_items.memory_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_memory_evidence_memory_id'), 'memory_evidence', ['memory_id'], unique=False)
    op.create_index('ix_memory_evidence_user_memory', 'memory_evidence', ['user_id', 'memory_id'], unique=False)
    op.create_table('rag_documents',
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('raw_file_path', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['rag_sources.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_rag_documents_content_hash'), 'rag_documents', ['content_hash'], unique=False)
    op.create_index('ix_rag_documents_owner_document', 'rag_documents', ['owner_user_id', 'document_id'], unique=True)
    op.create_index(op.f('ix_rag_documents_owner_user_id'), 'rag_documents', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_rag_documents_source_id'), 'rag_documents', ['source_id'], unique=False)
    op.create_table('trips',
    sa.Column('trip_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_index(op.f('ix_trips_session_id'), 'trips', ['session_id'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_index('ix_trips_user_session_trip', 'trips', ['user_id', 'session_id', 'trip_id'], unique=True)
    op.create_table('rag_chunks',
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_type', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('poi_id', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('theme', sa.String(length=64), nullable=True),
    sa.Column('travel_days', sa.Integer(), nullable=True),
    sa.Column('audience', sa.String(length=64), nullable=True),
    sa.Column('season', sa.String(length=32), nullable=True),
    sa.Column('price_level', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_rag_chunks_city'), 'rag_chunks', ['city'], unique=False)
    op.create_index(op.f('ix_rag_chunks_document_id'), 'rag_chunks', ['document_id'], unique=False)
    op.create_index('ix_rag_chunks_owner_chunk', 'rag_chunks', ['owner_user_id', 'chunk_id'], unique=True)
    op.create_index(op.f('ix_rag_chunks_owner_user_id'), 'rag_chunks', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_poi_id'), 'rag_chunks', ['poi_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_theme'), 'rag_chunks', ['theme'], unique=False)
    op.create_table('trip_feedback',
    sa.Column('feedback_id', sa.String(length=64), nullable=False),
    sa.Column('trip_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=64), nullable=True),
    sa.Column('activity_id', sa.String(length=128), nullable=True),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_trip_feedback_trip_id'), 'trip_feedback', ['trip_id'], unique=False)
    op.create_index('ix_trip_feedback_user_trip', 'trip_feedback', ['user_id', 'trip_id'], unique=False)
    op.create_table('trip_plan_versions',
    sa.Column('version_id', sa.String(length=64), nullable=False),
    sa.Column('trip_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('itinerary', sa.JSON(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('source_agent', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('trip_id', 'version_number', name='uq_trip_plan_version')
    )
    op.create_index(op.f('ix_trip_plan_versions_trip_id'), 'trip_plan_versions', ['trip_id'], unique=False)
    op.create_index('ix_trip_plan_versions_user_trip_version', 'trip_plan_versions', ['user_id', 'trip_id', 'version_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_plan_versions_user_trip_version', table_name='trip_plan_versions')
    op.drop_index(op.f('ix_trip_plan_versions_trip_id'), table_name='trip_plan_versions')
    op.drop_table('trip_plan_versions')
    op.drop_index('ix_trip_feedback_user_trip', table_name='trip_feedback')
    op.drop_index(op.f('ix_trip_feedback_trip_id'), table_name='trip_feedback')
    op.drop_table('trip_feedback')
    op.drop_index(op.f('ix_rag_chunks_theme'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_poi_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_owner_user_id'), table_name='rag_chunks')
    op.drop_index('ix_rag_chunks_owner_chunk', table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_document_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_city'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_index('ix_trips_user_session_trip', table_name='trips')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_session_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_rag_documents_source_id'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_owner_user_id'), table_name='rag_documents')
    op.drop_index('ix_rag_documents_owner_document', table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_content_hash'), table_name='rag_documents')
    op.drop_table('rag_documents')
    op.drop_index('ix_memory_evidence_user_memory', table_name='memory_evidence')
    op.drop_index(op.f('ix_memory_evidence_memory_id'), table_name='memory_evidence')
    op.drop_table('memory_evidence')
    op.drop_index('ix_chat_messages_user_session_message', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_rag_sources_owner_user_id'), table_name='rag_sources')
    op.drop_table('rag_sources')
    op.drop_index('ix_memory_items_user_memory', table_name='memory_items')
    op.drop_index(op.f('ix_memory_items_user_id'), table_name='memory_items')
    op.drop_table('memory_items')
    op.drop_index('ix_chat_sessions_user_session', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('users')
    op.drop_index('ix_tool_calls_user_session_trip', table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_user_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_trip_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_session_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_table('provider_health')
    # ### end Alembic commands ###
