"""add_user_profile_snapshot

Revision ID: edb70f27be69
Revises: f65880d1a05a
Create Date: 2026-09-29 17:28:00.166253
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'edb70f27be69'
down_revision: Union[str, None] = 'f65880d1a05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_profile')
    # ### end Alembic commands ###
