"""add_agent_state_snapshots

Revision ID: f65880d1a05a
Revises: a4b0c868ef89
Create Date: 2026-09-29 17:25:54.867231
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f65880d1a05a'
down_revision: Union[str, None] = 'a4b0c868ef89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('agent_state', sa.JSON(), nullable=True))
    op.add_column('chat_sessions', sa.Column('user_profile', sa.JSON(), nullable=True))
    op.add_column('trips', sa.Column('agent_state', sa.JSON(), nullable=True))
    op.add_column('trips', sa.Column('user_profile', sa.JSON(), nullable=True))
    op.add_column('trips', sa.Column('structured_itinerary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'structured_itinerary')
    op.drop_column('trips', 'user_profile')
    op.drop_column('trips', 'agent_state')
    op.drop_column('chat_sessions', 'user_profile')
    op.drop_column('chat_sessions', 'agent_state')
    # ### end Alembic commands ###
