<script setup lang="ts">
import { computed,nextTick,onMounted,ref,watch } from 'vue';import { useRoute,useRouter } from 'vue-router';import { Send,Sparkles,Bot,UserRound,LoaderCircle,ThumbsUp,ThumbsDown,Wrench,Quote } from '@lucide/vue';import { useAppStore } from '../stores/app';import { api,streamMessage } from '../services/api';import SessionSidebar from '../components/SessionSidebar.vue';import ItineraryPanel from '../components/ItineraryPanel.vue';import type { MessageItem,TripVersion } from '../types'
const app=useAppStore(),route=useRoute(),router=useRouter(),input=ref(''),sending=ref(false),streamStatus=ref(''),messageList=ref<HTMLElement|null>(null),currentItinerary=ref<TripVersion|null>(null)
const suggestions=['周末去苏州，两个人，想慢一点','帮我规划 5 天游北京，偏爱博物馆','带父母去杭州，少走路，多休息'],hasMessages=computed(()=>app.messages.length>0)
/** 加载目标会话的消息、旅行和最新行程版本。 */
async function load(id?:string){if(!app.sessions.length)await app.loadSessions().catch(()=>undefined);const target=id||String(route.params.sessionId||'')||app.activeSessionId;if(!target)return;await app.selectSession(target);const trip=app.activeTrip;currentItinerary.value=trip?(await api.tripVersions(trip.trip_id,trip.session_id)).at(-1)||null:null}
/** 确保发送消息前存在一个当前会话。 */
async function ensureSession(){if(app.activeSessionId)return app.activeSessionId;const s=await app.createSession();router.replace(`/chat/${s.session_id}`);return s.session_id}
/** 乐观插入消息、消费工作流 SSE 事件并刷新行程状态。 */
async function send(text=input.value){const message=text.trim();if(!message||sending.value)return;const sessionId=await ensureSession();input.value='';sending.value=true;app.messages.push({session_id:sessionId,user_id:app.userId,role:'user',content:message,created_at:new Date().toISOString()});const pending:MessageItem={session_id:sessionId,user_id:app.userId,role:'assistant',content:'',pending:true};app.messages.push(pending);await nextTick();messageList.value?.scrollTo({top:messageList.value.scrollHeight,behavior:'smooth'});try{await streamMessage(sessionId,message,(event,data)=>{if(event==='status')streamStatus.value=data.message;if(event==='message'){pending.content=data.response;pending.trace=data.node_trace;pending.errors=data.errors;pending.pending=false}if(event==='error')throw new Error(data.message)});await app.refreshCurrent();const trip=app.activeTrip;if(trip)currentItinerary.value=(await api.tripVersions(trip.trip_id,trip.session_id)).at(-1)||null}catch(error){pending.content=`抱歉，这次连接没有完成：${error instanceof Error?error.message:'未知错误'}`;pending.pending=false}finally{sending.value=false;streamStatus.value='';await nextTick();messageList.value?.scrollTo({top:messageList.value.scrollHeight,behavior:'smooth'})}}
/** 记录用户对当前行程版本的接受或拒绝反馈。 */
async function feedback(type:'accept'|'reject'){const trip=app.activeTrip;if(!trip)return app.showNotice('当前还没有可反馈的行程');await api.feedback(trip.trip_id,trip.session_id,{feedback_type:type,version_id:currentItinerary.value?.version_id});app.showNotice(type==='accept'?'已记下你喜欢这版方案':'已记下你的调整意向')}
onMounted(()=>load());watch(()=>route.params.sessionId,id=>load(String(id||'')))
</script>
<template><div class="chat-layout"><SessionSidebar/><section class="chat-main"><div ref="messageList" class="message-list"><div v-if="!hasMessages" class="chat-welcome"><span class="assistant-orbit"><Sparkles :size="26"/></span><span class="eyebrow">A THOUGHTFUL JOURNEY STARTS HERE</span><h2>今天，想去哪里走走？</h2><p>不需要一次说清所有细节。先告诉我一个念头，我们会一起把它变成旅程。</p><div class="suggestion-list"><button v-for="item in suggestions" :key="item" @click="send(item)">{{item}}</button></div></div><article v-for="(message,index) in app.messages" :key="message.message_id||index" class="message" :class="message.role"><span class="avatar"><component :is="message.role==='user'?UserRound:Bot" :size="18"/></span><div class="message-body"><small>{{message.role==='user'?'你':'TravelMind'}}</small><div v-if="message.pending" class="thinking"><LoaderCircle :size="16" class="spin"/>{{streamStatus||'正在整理路线、预算与偏好…'}}</div><p v-else>{{message.content}}</p><div v-if="message.trace?.length" class="tool-trace"><Wrench :size="13"/>{{message.trace.join(' → ')}}</div><div v-if="message.role==='assistant'&&!message.pending" class="message-actions"><button aria-label="喜欢这版方案" @click="feedback('accept')"><ThumbsUp :size="14"/></button><button aria-label="不喜欢这版方案" @click="feedback('reject')"><ThumbsDown :size="14"/></button><span><Quote :size="13"/>基于实时工具与已授权资料</span></div></div></article></div><form class="composer" @submit.prevent="send()"><textarea v-model="input" rows="1" placeholder="描述目的地、日期、预算或你在意的体验…" @keydown.enter.exact.prevent="send()"></textarea><button class="send-button" :disabled="!input.trim()||sending" aria-label="发送"><Send :size="19"/></button><small>Enter 发送 · Shift + Enter 换行 · 实时信息会标注来源</small></form></section><ItineraryPanel :itinerary="currentItinerary?.itinerary" compact/></div></template>
