<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import { Library,Plus,FileText,ExternalLink,Trash2,UploadCloud,Search,BadgeCheck,X } from '@lucide/vue';import { api } from '../services/api';import type { RagDocument,RagSource } from '../types';import { useAppStore } from '../stores/app';import EmptyState from '../components/EmptyState.vue'
const app=useAppStore(),sources=ref<RagSource[]>([]),documents=ref<RagDocument[]>([]),query=ref(''),showAdd=ref(false),form=ref({sourceName:'',sourceType:'guide',url:'',title:'',content:'',documentType:'guide',city:'',theme:''})
const visibleDocs=computed(()=>documents.value.filter(d=>d.title.toLowerCase().includes(query.value.toLowerCase()))),sourceMap=computed(()=>Object.fromEntries(sources.value.map(s=>[s.source_id,s])))
/** 并行加载当前用户可见的知识来源和文档。 */
async function load(){[sources.value,documents.value]=await Promise.all([api.sources(),api.documents()])}
/** 创建知识来源并把表单正文导入 RAG。 */
async function ingest(){const s=await api.createSource({source_type:form.value.sourceType,name:form.value.sourceName,url:form.value.url||null,authorization_status:'authorized'});await api.ingestDocument(s.source_id,{title:form.value.title,content:form.value.content,document_type:form.value.documentType,metadata:{city:form.value.city||null,theme:form.value.theme||null},embed:false});showAdd.value=false;form.value={sourceName:'',sourceType:'guide',url:'',title:'',content:'',documentType:'guide',city:'',theme:''};await load();app.showNotice('资料已进入知识库索引队列')}
/** 删除当前用户拥有的知识文档并更新页面列表。 */
async function remove(doc:RagDocument){await api.deleteDocument(doc.document_id);documents.value=documents.value.filter(i=>i.document_id!==doc.document_id)}
onMounted(load)
</script>
<template><div class="knowledge-layout"><section class="knowledge-hero paper-card"><div><span class="hero-kicker"><Library :size="15"/> TRUSTED TRAVEL LIBRARY</span><h2>把可靠资料，变成你的旅行判断力。</h2><p>导入已获授权的攻略、官方说明或自己的旅行笔记。TravelMind 会在回答中标注来源，而不是凭空补全事实。</p></div><button class="button primary" @click="showAdd=true"><Plus :size="17"/>添加资料</button></section><section class="paper-card knowledge-table"><div class="section-heading"><div><span class="eyebrow">SOURCES & DOCUMENTS</span><h2>已收录资料</h2></div><div class="search-field compact"><Search :size="16"/><input v-model="query" placeholder="搜索资料"></div></div><div v-if="visibleDocs.length" class="document-list"><article v-for="doc in visibleDocs" :key="doc.document_id"><span class="document-icon"><FileText :size="20"/></span><div><strong>{{doc.title}}</strong><small>{{sourceMap[doc.source_id]?.name||'未知来源'}} · {{doc.chunk_count}} 个知识片段</small></div><span class="auth-badge"><BadgeCheck :size="14"/>{{doc.is_public?'公共知识':'私人授权'}}</span><a v-if="sourceMap[doc.source_id]?.url" :href="sourceMap[doc.source_id].url" target="_blank" class="icon-button"><ExternalLink :size="15"/></a><button v-if="doc.can_delete" class="icon-button danger" @click="remove(doc)"><Trash2 :size="15"/></button></article></div><EmptyState v-else title="知识库等待第一份资料" description="你上传的内容只会在授权范围内检索，并保留来源与归属。"><button class="button secondary" @click="showAdd=true"><UploadCloud :size="17"/>导入文本资料</button></EmptyState></section><div v-if="showAdd" class="modal-backdrop" @click.self="showAdd=false"><form class="modal-card modal-wide" @submit.prevent="ingest"><div class="section-heading"><div><span class="eyebrow">ADD TO LIBRARY</span><h2>导入一份旅行资料</h2></div><button type="button" class="icon-button" @click="showAdd=false"><X :size="18"/></button></div><div class="field-row"><label>来源名称<input v-model="form.sourceName" placeholder="如：北京市文旅局" required></label><label>来源类型<select v-model="form.sourceType"><option value="official">官方事实</option><option value="guide">授权攻略</option><option value="template">行程模板</option></select></label></div><label>来源链接（可选）<input v-model="form.url" type="url" placeholder="https://"></label><label>文档标题<input v-model="form.title" required></label><div class="field-row"><label>城市<input v-model="form.city" placeholder="北京"></label><label>主题<input v-model="form.theme" placeholder="文化 / 美食 / 亲子"></label></div><label>正文内容<textarea v-model="form.content" rows="8" placeholder="粘贴你有权使用的资料正文…" required></textarea></label><button class="button primary" type="submit"><UploadCloud :size="17"/>授权并导入</button></form></div></div></template>
