<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import { Brain,Search,Pencil,Trash2,Download,ShieldCheck,ToggleLeft,ToggleRight,Save,X } from '@lucide/vue';import { api } from '../services/api';import type { MemoryItem } from '../types';import { useAppStore } from '../stores/app';import EmptyState from '../components/EmptyState.vue'
const app=useAppStore(),items=ref<MemoryItem[]>([]),query=ref(''),settings=ref({personalization_enabled:true,long_term_memory_enabled:true}),editing=ref<MemoryItem|null>(null),draft=ref(''),labels:Record<string,string>={explicit:'明确偏好',semantic:'稳定习惯',scenario:'场景偏好',episodic:'旅行经历'}
const filtered=computed(()=>items.value.filter(i=>`${i.statement}${i.category}${i.scope}`.toLowerCase().includes(query.value.toLowerCase()))),groups=computed(()=>['explicit','semantic','scenario','episodic'].map(type=>({type,items:filtered.value.filter(i=>i.memory_type===type)})).filter(g=>g.items.length))
/** 并行加载长期记忆和用户的 Memory 开关。 */
async function load(){[items.value,settings.value]=await Promise.all([api.memories(),api.memorySettings()])}
/** 切换个性化或长期记忆设置。 */
async function toggle(key:'personalization_enabled'|'long_term_memory_enabled'){settings.value=await api.updateMemorySettings({[key]:!settings.value[key]})}
/** 打开指定记忆的编辑状态并复制原始陈述。 */
function startEdit(i:MemoryItem){editing.value=i;draft.value=i.statement}
/** 保存用户修改后的记忆陈述。 */
async function save(){if(!editing.value)return;const u=await api.updateMemory(editing.value.memory_id,draft.value);items.value=items.value.map(i=>i.memory_id===u.memory_id?u:i);editing.value=null;app.showNotice('记忆已更新')}
/** 删除一条长期记忆并同步页面状态。 */
async function remove(id:string){await api.deleteMemory(id);items.value=items.value.filter(i=>i.memory_id!==id)}
/** 将当前用户的记忆列表下载为 JSON 文件。 */
function exportAll(){const b=new Blob([JSON.stringify(items.value,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`travelmind-memory-${app.userId}.json`;a.click();URL.revokeObjectURL(a.href)}
onMounted(load)
</script>
<template><div class="memory-layout"><section class="privacy-banner paper-card"><span><ShieldCheck :size="24"/></span><div><h2>这些记忆只属于你</h2><p>你可以查看、修改或删除任何一条。当前旅行中的明确要求永远优先于长期偏好。</p></div></section><section class="memory-controls paper-card"><div class="control-row"><div><strong>个性化推荐</strong><small>让偏好参与景点与节奏排序</small></div><button class="toggle" :class="{on:settings.personalization_enabled}" @click="toggle('personalization_enabled')"><component :is="settings.personalization_enabled?ToggleRight:ToggleLeft" :size="34"/></button></div><div class="control-row"><div><strong>长期记忆</strong><small>在未来旅程中复用稳定偏好</small></div><button class="toggle" :class="{on:settings.long_term_memory_enabled}" @click="toggle('long_term_memory_enabled')"><component :is="settings.long_term_memory_enabled?ToggleRight:ToggleLeft" :size="34"/></button></div></section><section class="memory-content paper-card"><div class="section-heading"><div><span class="eyebrow">MEMORY ATLAS</span><h2>系统对你的了解</h2></div><button class="button secondary" @click="exportAll"><Download :size="16"/>导出</button></div><div class="search-field"><Search :size="17"/><input v-model="query" placeholder="搜索偏好、场景或旅行经历"></div><div v-if="groups.length" class="memory-groups"><section v-for="group in groups" :key="group.type"><div class="memory-group-title"><Brain :size="17"/><strong>{{labels[group.type]||group.type}}</strong><span>{{group.items.length}}</span></div><article v-for="item in group.items" :key="item.memory_id" class="memory-row"><div><p>{{item.statement}}</p><small>{{item.category}} · {{item.scope}} · 置信度 {{Math.round(item.confidence*100)}}%</small></div><div><button class="icon-button" @click="startEdit(item)"><Pencil :size="15"/></button><button class="icon-button danger" @click="remove(item.memory_id)"><Trash2 :size="15"/></button></div></article></section></div><EmptyState v-else title="还没有形成长期记忆" description="当你明确说“请记住”，或多次表达相同偏好时，记忆会出现在这里。"/></section><div v-if="editing" class="modal-backdrop" @click.self="editing=null"><form class="modal-card" @submit.prevent="save"><div class="section-heading"><div><span class="eyebrow">EDIT MEMORY</span><h2>修改这条记忆</h2></div><button type="button" class="icon-button" @click="editing=null"><X :size="18"/></button></div><label>记忆内容<textarea v-model="draft" rows="4" required></textarea></label><button class="button primary"><Save :size="17"/>保存修改</button></form></div></div></template>
