<script setup lang="ts">
import { onMounted,ref } from 'vue';import { UserRound,Map,Cpu,Shield,Save,Server,CheckCircle2,AlertCircle } from '@lucide/vue';import { api } from '../services/api';import { useAppStore } from '../stores/app'
const app=useAppStore(),identity=ref(app.userId),amapKey=ref(localStorage.getItem('travelmind_amap_key')||''),amapSecurity=ref(localStorage.getItem('travelmind_amap_security')||''),providers=ref<Record<string,Record<string,any>>>({});
/** 保存并切换当前浏览器使用的本地用户身份。 */
function saveIdentity(){app.switchUser(identity.value)}
/** 将高德 Web Key 和安全密钥保存到当前浏览器。 */
function saveMap(){localStorage.setItem('travelmind_amap_key',amapKey.value.trim());localStorage.setItem('travelmind_amap_security',amapSecurity.value.trim());app.showNotice('地图设置已保存在当前浏览器')}
onMounted(async()=>{providers.value=await api.toolHealth().catch(()=>({}))})
</script>
<template><div class="settings-layout"><section class="settings-intro paper-card"><span><Shield :size="24"/></span><div><h2>你掌控身份、记忆和外部服务</h2><p>密钥只保存在当前浏览器；服务端模型与工具凭据仍由后端环境变量管理。</p></div></section><section class="settings-card paper-card"><div class="settings-icon"><UserRound :size="22"/></div><div class="settings-copy"><span class="eyebrow">LOCAL IDENTITY</span><h2>本地身份</h2><p>不同身份之间的会话、行程、记忆和私有知识严格隔离。</p><label>用户 ID<input v-model="identity" minlength="3" maxlength="64"></label><button class="button secondary" @click="saveIdentity"><Save :size="16"/>切换身份</button></div></section><section class="settings-card paper-card"><div class="settings-icon"><Map :size="22"/></div><div class="settings-copy"><span class="eyebrow">AMAP JS API</span><h2>高德交互地图</h2><p>未填写 Key 时，行程页仍提供轻量路线视图；填写后启用真实标点与连线。</p><label>Web JS Key<input v-model="amapKey" type="password" placeholder="仅保存在 localStorage"></label><label>安全密钥（可选）<input v-model="amapSecurity" type="password"></label><button class="button secondary" @click="saveMap"><Save :size="16"/>保存地图设置</button></div></section><section class="settings-card paper-card full"><div class="settings-icon"><Server :size="22"/></div><div class="settings-copy"><span class="eyebrow">PROVIDER HEALTH</span><h2>实时服务状态</h2><p>“未配置”的 Provider 不会被模型用来编造实时事实。</p><div class="provider-grid"><div v-for="(value,name) in providers" :key="name"><component :is="value.status==='healthy'?CheckCircle2:AlertCircle" :size="18"/><span><strong>{{name}}</strong><small>{{value.configured===false?'未配置':value.status||'等待首次调用'}} · {{(value.tools||[]).length}} 个工具</small></span></div></div></div></section><section class="settings-card paper-card full"><div class="settings-icon"><Cpu :size="22"/></div><div class="settings-copy"><span class="eyebrow">MODEL RUNTIME</span><h2>模型与隐私策略</h2><p>模型名称、API 凭据、日志脱敏和 CORS 白名单由后端安全配置管理，前端不会读取或回显 Secret。</p><div class="readonly-setting"><span>当前模式</span><strong>后端托管 · DeepSeek / Qwen 兼容</strong></div></div></section></div></template>
